package enderdom.eddie.junit.bio.sequence;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import enderdom.eddie.tools.bio.Tools_String_Bio;

public class ProteinTest {

	@Test
	public void testTranslate(){
		
		String prot = "MKALLLLVLVSFAREGLSAPQEDLITNLPGLTWQPNFKQYSGYLQAAGTKKLHYWFVESS"+
		"SRPATDPVVLWLNGGPGCSSLDGFLTEHGPFRVNDDXGQNLTANPYSWNQITNIIYLESP"+
		"AGVGFSYSDDANYTTDDDEVANQQPPRLARLLQE";
		String est = "ATGAAAGCACTGTTGCTGCTTGTTCTTGTGAGCTTTGCCAGAGAAGGACTTTCAGCCCCT"+
				"CAGGAGGATTTGATCACAAACCTTCCGGGTCTGACATGGCAGCCGAACTTCAAGCAGTAT"+
				"TCTGGCTATCTTCAGGCAGCCGGCACTAAGAAGCTCCACTATTGGTTTGTTGAGTCGTCA"+
				"AGTAGACCAGCGACAGATCCGGTTGTGCTTTGGCTGAATGGGGGACCAGGATGTAGCTCG"+
				"CTGGATGGGTTCCTCACAGAGCATGGACCTTTTAGGGTGAATGACGATXTGGGTCAAAAC"+
				"CTGACAGCAAATCCGTATTCCTGGAACCAGATTACCAACATAATTTACCTGGAGTCTCCA"+
				"GCAGGTGTCGGCTTCTCCTACTCTGACGACGCTAACTACACCACTGATGATGATGAGGTC"+
				"GCCAACCAACAACCACCTCGCCTTGCAAGACTTCTTCAGGAA";
		String prot2 = Tools_String_Bio.translate(est, 0, false);
		assertEquals("Result", prot, prot2);
	}
	
}
